// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Slottet.Infrastructure.Data;

#nullable disable

namespace Slottet.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Slottet.Domain.Entity.MedicineStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Administered")
                        .HasColumnType("bit");

                    b.Property<int>("ResidentSchemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ResidentSchemaId");

                    b.ToTable("MedicineStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Administered = true,
                            ResidentSchemaId = 1,
                            Time = new DateTime(2026, 3, 27, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Slottet.Domain.Entity.ResidentSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Employee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrafficLight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ResidentSchemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Employee = "Susanne",
                            Name = "Janne",
                            Note = "...",
                            TrafficLight = 1
                        });
                });

            modelBuilder.Entity("Slottet.Domain.Entity.MedicineStatus", b =>
                {
                    b.HasOne("Slottet.Domain.Entity.ResidentSchema", "ResidentSchema")
                        .WithMany("MedicineStatuses")
                        .HasForeignKey("ResidentSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResidentSchema");
                });

            modelBuilder.Entity("Slottet.Domain.Entity.ResidentSchema", b =>
                {
                    b.Navigation("MedicineStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
